version: '3.9'

services:
  # minecraft server
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "8080:8080"
    environment:
      # rcon
      ENABLE_RCON: true
      RCON_PASSWORD: "${RCON_PASSWORD}"
      # minecraft
      TYPE: "PAPER"
      VERSION: 1.20.1
      EULA: "TRUE"
      ONLINE_MODE: false
      DIFFICULTY: "hard"
      MOTD: ${MOTD}
      ICON: "/icon/icon.png"
      # server 
      MEMORY: ${MEMORY}
      SERVER_NAME: "твоямама.рф"
      GUI: "FALSE"
    volumes:
      - ./minecraft/data:/data
      - ./minecraft/icon:/icon
      - ./minecraft/plugins:/data/plugins
    restart: always
    user: root

  # depend
  # rcon web ui
  rcon:
    image: itzg/rcon
    ports:
      - "4327:4327"
    environment:
      # web auth data
      - RWA_PASSWORD=${RCON_WEB_PASSWORD}
      # rcon connection data
      - RWA_RCON_HOST=mc
      - RWA_RCON_PASSWORD=${RCON_PASSWORD}
    volumes:
      - ./minecraft/rcon-web-admin/db:/opt/rcon-web-admin/db
    user: root

  #metrics
  mcmonitor:
    image: itzg/mc-monitor
    command: export-for-prometheus
    environment:
      EXPORT_SERVERS: mc
    depends_on:
      - mc

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    user: root

  prometheus:
    image: prom/prometheus
    volumes:
      - ./metrics/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./metrics/prometheus/db/prometheus:/prometheus
    depends_on:
      - mcmonitor
      - cadvisor
    user: root

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - ./metrics/grafana/lib:/var/lib/grafana
      - ./metrics/grafana/provisioning:/etc/grafana/provisioning
      - ./metrics/grafana/dashboards:/etc/grafana/dashboards
      - ./metrics/grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - prometheus
    user: root

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./static:/etc/nginx/html
    ports:
      - "80:80"
    depends_on:
      - grafana
      - mc
      - rcon
    restart: always
    user: root
