global:
  scrape_interval: 5s
scrape_configs:
  - job_name: mc-monitor
    static_configs:
      - targets:
          - mcmonitor:8080
          
  - job_name: cadvisor
    static_configs:
      - targets: 
          - cadvisor:8080