global:
  scrape_interval: 5s
scrape_configs:
  - job_name: mc-monitor
    static_configs:
      - targets:
          - mcmonitor:8080
  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100