{
 "title": "Minecraft Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Minecraft Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{container_label_com_docker_compose_service=\"mc\"}[1m])",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Usage Server Mem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"mc\"}",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  { "title": "Minecraft Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Server healthy",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minecraft_status_healthy", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Server response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "minecraft_status_response_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Player Online",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "minecraft_status_players_online_count",
     "legendFormat": "Online"
    },
    {
     "expr": "minecraft_status_players_max_count",
     "legendFormat": "MaxOnline"
    }
   ]
  }
 ]
}